// Code generated by "stringer -type=EquipmentSlot"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EquipmentSlotNone-0]
	_ = x[EquipmentSlotAmulet-1]
	_ = x[EquipmentSlotHand-2]
	_ = x[EquipmentSlotLRing-3]
	_ = x[EquipmentSlotRRing-4]
	_ = x[EquipmentSlotHead-5]
	_ = x[EquipmentSlotTorso-6]
	_ = x[EquipmentSlotFoot-7]
	_ = x[EquipmentSlotShoulder-8]
	_ = x[EquipmentSlotNone2-9]
	_ = x[EquipmentSlotWeapon-10]
	_ = x[EquipmentSlotOffhand-11]
}

const _EquipmentSlot_name = "EquipmentSlotNoneEquipmentSlotAmuletEquipmentSlotHandEquipmentSlotLRingEquipmentSlotRRingEquipmentSlotHeadEquipmentSlotTorsoEquipmentSlotFootEquipmentSlotShoulderEquipmentSlotNone2EquipmentSlotWeaponEquipmentSlotOffhand"

var _EquipmentSlot_index = [...]uint8{0, 17, 36, 53, 71, 89, 106, 124, 141, 162, 180, 199, 219}

func (i EquipmentSlot) String() string {
	if i >= EquipmentSlot(len(_EquipmentSlot_index)-1) {
		return "EquipmentSlot(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EquipmentSlot_name[_EquipmentSlot_index[i]:_EquipmentSlot_index[i+1]]
}
