// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionUnSpawn interface {
	GetActionUnSpawn() *ActionUnSpawn
}

func (a *ActionUnSpawn) GetActionUnSpawn() *ActionUnSpawn {
	return a
}

func registerLuaActionUnSpawn(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionUnSpawn")
	state.SetGlobal("ActionUnSpawn", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionUnSpawn))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionUnSpawn(),
	))
}

func luaMethodsActionUnSpawn() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUnSpawn](l, 1)
			obj := objInterface.GetActionUnSpawn()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUnSpawn](l, 1)
			obj := objInterface.GetActionUnSpawn()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionUnSpawn": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUnSpawn](l, 1)
			obj := objInterface.GetActionUnSpawn()
			res0 := obj.GetActionUnSpawn()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionUnSpawn(l *lua2.LState) int {
	obj := NewActionUnSpawn()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionUnSpawn"))
	l.Push(ud)
	return 1
}

func (a *ActionUnSpawn) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionUnSpawn"))
	return ud
}
