// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionKill interface {
	GetActionKill() *ActionKill
}

func (a *ActionKill) GetActionKill() *ActionKill {
	return a
}

func registerLuaActionKill(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionKill")
	state.SetGlobal("ActionKill", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionKill))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionKill(),
	))
}

func luaMethodsActionKill() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionKill](l, 1)
			obj := objInterface.GetActionKill()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionKill](l, 1)
			obj := objInterface.GetActionKill()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}
func newLuaActionKill(l *lua2.LState) int {
	obj := NewActionKill()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionKill"))
	l.Push(ud)
	return 1
}

func (a *ActionKill) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionKill"))
	return ud
}
