// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionStun interface {
	GetActionStun() *ActionStun
}

func (a *ActionStun) GetActionStun() *ActionStun {
	return a
}

func registerLuaActionStun(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionStun")
	state.SetGlobal("ActionStun", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionStun))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionStun(),
	))
}

func luaMethodsActionStun() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionStun](l, 1)
			obj := objInterface.GetActionStun()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionStun](l, 1)
			obj := objInterface.GetActionStun()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionStun": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionStun](l, 1)
			obj := objInterface.GetActionStun()
			res0 := obj.GetActionStun()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionStun(l *lua2.LState) int {
	obj := NewActionStun()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionStun"))
	l.Push(ud)
	return 1
}

func (a *ActionStun) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionStun"))
	return ud
}
