// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionConvertItemsToGold interface {
	GetActionConvertItemsToGold() *ActionConvertItemsToGold
}

func (a *ActionConvertItemsToGold) GetActionConvertItemsToGold() *ActionConvertItemsToGold {
	return a
}

func registerLuaActionConvertItemsToGold(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionConvertItemsToGold")
	state.SetGlobal("ActionConvertItemsToGold", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionConvertItemsToGold))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionConvertItemsToGold(),
	))
}

func luaMethodsActionConvertItemsToGold() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionConvertItemsToGold](l, 1)
			obj := objInterface.GetActionConvertItemsToGold()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionConvertItemsToGold](l, 1)
			obj := objInterface.GetActionConvertItemsToGold()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}
func newLuaActionConvertItemsToGold(l *lua2.LState) int {
	obj := NewActionConvertItemsToGold()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionConvertItemsToGold"))
	l.Push(ud)
	return 1
}

func (a *ActionConvertItemsToGold) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionConvertItemsToGold"))
	return ud
}
