// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionMoveInDirectionAction interface {
	GetActionMoveInDirectionAction() *ActionMoveInDirectionAction
}

func (a *ActionMoveInDirectionAction) GetActionMoveInDirectionAction() *ActionMoveInDirectionAction {
	return a
}

func registerLuaActionMoveInDirectionAction(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionMoveInDirectionAction")
	state.SetGlobal("ActionMoveInDirectionAction", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionMoveInDirectionAction))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionMoveInDirectionAction(),
	))
}

func luaMethodsActionMoveInDirectionAction() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionMoveInDirectionAction](l, 1)
			obj := objInterface.GetActionMoveInDirectionAction()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionMoveInDirectionAction](l, 1)
			obj := objInterface.GetActionMoveInDirectionAction()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}
func newLuaActionMoveInDirectionAction(l *lua2.LState) int {
	obj := NewActionMoveInDirectionAction()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionMoveInDirectionAction"))
	l.Push(ud)
	return 1
}

func (a *ActionMoveInDirectionAction) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionMoveInDirectionAction"))
	return ud
}
