// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionUseItemTarget interface {
	GetActionUseItemTarget() *ActionUseItemTarget
}

func (a *ActionUseItemTarget) GetActionUseItemTarget() *ActionUseItemTarget {
	return a
}

func registerLuaActionUseItemTarget(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionUseItemTarget")
	state.SetGlobal("ActionUseItemTarget", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionUseItemTarget))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionUseItemTarget(),
	))
}

func luaMethodsActionUseItemTarget() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUseItemTarget](l, 1)
			obj := objInterface.GetActionUseItemTarget()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUseItemTarget](l, 1)
			obj := objInterface.GetActionUseItemTarget()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"getActionUseItemTarget": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUseItemTarget](l, 1)
			obj := objInterface.GetActionUseItemTarget()
			res0 := obj.GetActionUseItemTarget()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionUseItemTarget(l *lua2.LState) int {
	obj := NewActionUseItemTarget()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionUseItemTarget"))
	l.Push(ud)
	return 1
}

func (a *ActionUseItemTarget) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionUseItemTarget"))
	return ud
}
