// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	"RainbowRunner/pkg/datatypes"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionWarpTo interface {
	GetActionWarpTo() *ActionWarpTo
}

func (a *ActionWarpTo) GetActionWarpTo() *ActionWarpTo {
	return a
}

func registerLuaActionWarpTo(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionWarpTo")
	state.SetGlobal("ActionWarpTo", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionWarpTo(),
	))
}

func luaMethodsActionWarpTo() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"position": lua.LuaGenericGetSetValue[IActionWarpTo, datatypes.Vector3Float32](func(v IActionWarpTo) *datatypes.Vector3Float32 { return &v.GetActionWarpTo().Position }),
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionWarpTo](l, 1)
			obj := objInterface.GetActionWarpTo()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionWarpTo](l, 1)
			obj := objInterface.GetActionWarpTo()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"getActionWarpTo": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionWarpTo](l, 1)
			obj := objInterface.GetActionWarpTo()
			res0 := obj.GetActionWarpTo()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}

func (a *ActionWarpTo) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionWarpTo"))
	return ud
}
