// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionMoveTo interface {
	GetActionMoveTo() *ActionMoveTo
}

func (a *ActionMoveTo) GetActionMoveTo() *ActionMoveTo {
	return a
}

func registerLuaActionMoveTo(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionMoveTo")
	state.SetGlobal("ActionMoveTo", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionMoveTo))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionMoveTo(),
	))
}

func luaMethodsActionMoveTo() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"posX": lua.LuaGenericGetSetNumber[IActionMoveTo](func(v IActionMoveTo) *float32 { return &v.GetActionMoveTo().PosX }),
		"posY": lua.LuaGenericGetSetNumber[IActionMoveTo](func(v IActionMoveTo) *float32 { return &v.GetActionMoveTo().PosY }),

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionMoveTo](l, 1)
			obj := objInterface.GetActionMoveTo()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionMoveTo](l, 1)
			obj := objInterface.GetActionMoveTo()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionMoveTo": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionMoveTo](l, 1)
			obj := objInterface.GetActionMoveTo()
			res0 := obj.GetActionMoveTo()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionMoveTo(l *lua2.LState) int {
	obj := NewActionMoveTo()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionMoveTo"))
	l.Push(ud)
	return 1
}

func (a *ActionMoveTo) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionMoveTo"))
	return ud
}
