// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionRetrieveItem interface {
	GetActionRetrieveItem() *ActionRetrieveItem
}

func (a *ActionRetrieveItem) GetActionRetrieveItem() *ActionRetrieveItem {
	return a
}

func registerLuaActionRetrieveItem(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionRetrieveItem")
	state.SetGlobal("ActionRetrieveItem", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionRetrieveItem))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionRetrieveItem(),
	))
}

func luaMethodsActionRetrieveItem() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionRetrieveItem](l, 1)
			obj := objInterface.GetActionRetrieveItem()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionRetrieveItem](l, 1)
			obj := objInterface.GetActionRetrieveItem()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionRetrieveItem": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionRetrieveItem](l, 1)
			obj := objInterface.GetActionRetrieveItem()
			res0 := obj.GetActionRetrieveItem()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionRetrieveItem(l *lua2.LState) int {
	obj := NewActionRetrieveItem()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionRetrieveItem"))
	l.Push(ud)
	return 1
}

func (a *ActionRetrieveItem) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionRetrieveItem"))
	return ud
}
