// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionDodge interface {
	GetActionDodge() *ActionDodge
}

func (a *ActionDodge) GetActionDodge() *ActionDodge {
	return a
}

func registerLuaActionDodge(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionDodge")
	state.SetGlobal("ActionDodge", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionDodge))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionDodge(),
	))
}

func luaMethodsActionDodge() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionDodge](l, 1)
			obj := objInterface.GetActionDodge()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionDodge](l, 1)
			obj := objInterface.GetActionDodge()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionDodge": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionDodge](l, 1)
			obj := objInterface.GetActionDodge()
			res0 := obj.GetActionDodge()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionDodge(l *lua2.LState) int {
	obj := NewActionDodge()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionDodge"))
	l.Push(ud)
	return 1
}

func (a *ActionDodge) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionDodge"))
	return ud
}
