// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionFollow interface {
	GetActionFollow() *ActionFollow
}

func (a *ActionFollow) GetActionFollow() *ActionFollow {
	return a
}

func registerLuaActionFollow(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionFollow")
	state.SetGlobal("ActionFollow", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionFollow))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionFollow(),
	))
}

func luaMethodsActionFollow() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionFollow](l, 1)
			obj := objInterface.GetActionFollow()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionFollow](l, 1)
			obj := objInterface.GetActionFollow()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionFollow": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionFollow](l, 1)
			obj := objInterface.GetActionFollow()
			res0 := obj.GetActionFollow()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionFollow(l *lua2.LState) int {
	obj := NewActionFollow()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionFollow"))
	l.Push(ud)
	return 1
}

func (a *ActionFollow) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionFollow"))
	return ud
}
