// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionImmobilize interface {
	GetActionImmobilize() *ActionImmobilize
}

func (a *ActionImmobilize) GetActionImmobilize() *ActionImmobilize {
	return a
}

func registerLuaActionImmobilize(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionImmobilize")
	state.SetGlobal("ActionImmobilize", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionImmobilize))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionImmobilize(),
	))
}

func luaMethodsActionImmobilize() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionImmobilize](l, 1)
			obj := objInterface.GetActionImmobilize()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionImmobilize](l, 1)
			obj := objInterface.GetActionImmobilize()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}
func newLuaActionImmobilize(l *lua2.LState) int {
	obj := NewActionImmobilize()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionImmobilize"))
	l.Push(ud)
	return 1
}

func (a *ActionImmobilize) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionImmobilize"))
	return ud
}
