// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionRemove interface {
	GetActionRemove() *ActionRemove
}

func (a *ActionRemove) GetActionRemove() *ActionRemove {
	return a
}

func registerLuaActionRemove(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionRemove")
	state.SetGlobal("ActionRemove", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionRemove))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionRemove(),
	))
}

func luaMethodsActionRemove() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionRemove](l, 1)
			obj := objInterface.GetActionRemove()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionRemove](l, 1)
			obj := objInterface.GetActionRemove()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}
func newLuaActionRemove(l *lua2.LState) int {
	obj := NewActionRemove()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionRemove"))
	l.Push(ud)
	return 1
}

func (a *ActionRemove) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionRemove"))
	return ud
}
