// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionSpawn interface {
	GetActionSpawn() *ActionSpawn
}

func (a *ActionSpawn) GetActionSpawn() *ActionSpawn {
	return a
}

func registerLuaActionSpawn(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionSpawn")
	state.SetGlobal("ActionSpawn", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionSpawn))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionSpawn(),
	))
}

func luaMethodsActionSpawn() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSpawn](l, 1)
			obj := objInterface.GetActionSpawn()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSpawn](l, 1)
			obj := objInterface.GetActionSpawn()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"getActionSpawn": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSpawn](l, 1)
			obj := objInterface.GetActionSpawn()
			res0 := obj.GetActionSpawn()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionSpawn(l *lua2.LState) int {
	obj := NewActionSpawn()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionSpawn"))
	l.Push(ud)
	return 1
}

func (a *ActionSpawn) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionSpawn"))
	return ud
}
