// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionSpawnAnimation interface {
	GetActionSpawnAnimation() *ActionSpawnAnimation
}

func (a *ActionSpawnAnimation) GetActionSpawnAnimation() *ActionSpawnAnimation {
	return a
}

func registerLuaActionSpawnAnimation(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionSpawnAnimation")
	state.SetGlobal("ActionSpawnAnimation", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionSpawnAnimation))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionSpawnAnimation(),
	))
}

func luaMethodsActionSpawnAnimation() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSpawnAnimation](l, 1)
			obj := objInterface.GetActionSpawnAnimation()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSpawnAnimation](l, 1)
			obj := objInterface.GetActionSpawnAnimation()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"getActionSpawnAnimation": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSpawnAnimation](l, 1)
			obj := objInterface.GetActionSpawnAnimation()
			res0 := obj.GetActionSpawnAnimation()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionSpawnAnimation(l *lua2.LState) int {
	obj := NewActionSpawnAnimation()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionSpawnAnimation"))
	l.Push(ud)
	return 1
}

func (a *ActionSpawnAnimation) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionSpawnAnimation"))
	return ud
}
