// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionPlayAnimation interface {
	GetActionPlayAnimation() *ActionPlayAnimation
}

func (a *ActionPlayAnimation) GetActionPlayAnimation() *ActionPlayAnimation {
	return a
}

func registerLuaActionPlayAnimation(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionPlayAnimation")
	state.SetGlobal("ActionPlayAnimation", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionPlayAnimation(),
	))
}

func luaMethodsActionPlayAnimation() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"unk0": lua.LuaGenericGetSetNumber[IActionPlayAnimation](func(v IActionPlayAnimation) *byte { return &v.GetActionPlayAnimation().Unk0 }),
		"unk1": lua.LuaGenericGetSetNumber[IActionPlayAnimation](func(v IActionPlayAnimation) *uint32 { return &v.GetActionPlayAnimation().Unk1 }),
		"unk2": lua.LuaGenericGetSetNumber[IActionPlayAnimation](func(v IActionPlayAnimation) *uint32 { return &v.GetActionPlayAnimation().Unk2 }),
		"unk3": lua.LuaGenericGetSetNumber[IActionPlayAnimation](func(v IActionPlayAnimation) *uint32 { return &v.GetActionPlayAnimation().Unk3 }),
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionPlayAnimation](l, 1)
			obj := objInterface.GetActionPlayAnimation()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionPlayAnimation](l, 1)
			obj := objInterface.GetActionPlayAnimation()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (a *ActionPlayAnimation) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionPlayAnimation"))
	return ud
}
