// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionSearchForAttack interface {
	GetActionSearchForAttack() *ActionSearchForAttack
}

func (a *ActionSearchForAttack) GetActionSearchForAttack() *ActionSearchForAttack {
	return a
}

func registerLuaActionSearchForAttack(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionSearchForAttack")
	state.SetGlobal("ActionSearchForAttack", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionSearchForAttack))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionSearchForAttack(),
	))
}

func luaMethodsActionSearchForAttack() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSearchForAttack](l, 1)
			obj := objInterface.GetActionSearchForAttack()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSearchForAttack](l, 1)
			obj := objInterface.GetActionSearchForAttack()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"getActionSearchForAttack": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionSearchForAttack](l, 1)
			obj := objInterface.GetActionSearchForAttack()
			res0 := obj.GetActionSearchForAttack()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionSearchForAttack(l *lua2.LState) int {
	obj := NewActionSearchForAttack()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionSearchForAttack"))
	l.Push(ud)
	return 1
}

func (a *ActionSearchForAttack) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionSearchForAttack"))
	return ud
}
