// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionUseItem interface {
	GetActionUseItem() *ActionUseItem
}

func (a *ActionUseItem) GetActionUseItem() *ActionUseItem {
	return a
}

func registerLuaActionUseItem(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionUseItem")
	state.SetGlobal("ActionUseItem", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionUseItem))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionUseItem(),
	))
}

func luaMethodsActionUseItem() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUseItem](l, 1)
			obj := objInterface.GetActionUseItem()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUseItem](l, 1)
			obj := objInterface.GetActionUseItem()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"getActionUseItem": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionUseItem](l, 1)
			obj := objInterface.GetActionUseItem()
			res0 := obj.GetActionUseItem()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionUseItem(l *lua2.LState) int {
	obj := NewActionUseItem()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionUseItem"))
	l.Push(ud)
	return 1
}

func (a *ActionUseItem) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionUseItem"))
	return ud
}
