// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionKnockBack interface {
	GetActionKnockBack() *ActionKnockBack
}

func (a *ActionKnockBack) GetActionKnockBack() *ActionKnockBack {
	return a
}

func registerLuaActionKnockBack(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionKnockBack")
	state.SetGlobal("ActionKnockBack", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionKnockBack))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionKnockBack(),
	))
}

func luaMethodsActionKnockBack() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionKnockBack](l, 1)
			obj := objInterface.GetActionKnockBack()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionKnockBack](l, 1)
			obj := objInterface.GetActionKnockBack()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionKnockBack": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionKnockBack](l, 1)
			obj := objInterface.GetActionKnockBack()
			res0 := obj.GetActionKnockBack()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionKnockBack(l *lua2.LState) int {
	obj := NewActionKnockBack()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionKnockBack"))
	l.Push(ud)
	return 1
}

func (a *ActionKnockBack) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionKnockBack"))
	return ud
}
