// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionKnockDown interface {
	GetActionKnockDown() *ActionKnockDown
}

func (a *ActionKnockDown) GetActionKnockDown() *ActionKnockDown {
	return a
}

func registerLuaActionKnockDown(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionKnockDown")
	state.SetGlobal("ActionKnockDown", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionKnockDown))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionKnockDown(),
	))
}

func luaMethodsActionKnockDown() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionKnockDown](l, 1)
			obj := objInterface.GetActionKnockDown()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionKnockDown](l, 1)
			obj := objInterface.GetActionKnockDown()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionKnockDown": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionKnockDown](l, 1)
			obj := objInterface.GetActionKnockDown()
			res0 := obj.GetActionKnockDown()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionKnockDown(l *lua2.LState) int {
	obj := NewActionKnockDown()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionKnockDown"))
	l.Push(ud)
	return 1
}

func (a *ActionKnockDown) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionKnockDown"))
	return ud
}
