// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActionDie interface {
	GetActionDie() *ActionDie
}

func (a *ActionDie) GetActionDie() *ActionDie {
	return a
}

func registerLuaActionDie(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActionDie")
	state.SetGlobal("ActionDie", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActionDie))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActionDie(),
	))
}

func luaMethodsActionDie() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionDie](l, 1)
			obj := objInterface.GetActionDie()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},

		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionDie](l, 1)
			obj := objInterface.GetActionDie()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getActionDie": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActionDie](l, 1)
			obj := objInterface.GetActionDie()
			res0 := obj.GetActionDie()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaActionDie(l *lua2.LState) int {
	obj := NewActionDie()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActionDie"))
	l.Push(ud)
	return 1
}

func (a *ActionDie) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActionDie"))
	return ud
}
