// Code generated by "stringer -type=DRObjectType"; DO NOT EDIT.

package drobjecttypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DRObjectEntity-0]
	_ = x[DRObjectComponent-1]
	_ = x[DRObjectOther-2]
	_ = x[DRObjectManager-3]
	_ = x[DRObjectUnknown-4]
}

const _DRObjectType_name = "DRObjectEntityDRObjectComponentDRObjectOtherDRObjectManagerDRObjectUnknown"

var _DRObjectType_index = [...]uint8{0, 14, 31, 44, 59, 74}

func (i DRObjectType) String() string {
	if i < 0 || i >= DRObjectType(len(_DRObjectType_index)-1) {
		return "DRObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DRObjectType_name[_DRObjectType_index[i]:_DRObjectType_index[i+1]]
}
