// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IMoveInDirectionAction interface {
	GetMoveInDirectionAction() *MoveInDirectionAction
}

func (m *MoveInDirectionAction) GetMoveInDirectionAction() *MoveInDirectionAction {
	return m
}

func registerLuaMoveInDirectionAction(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("MoveInDirectionAction")
	state.SetGlobal("MoveInDirectionAction", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsMoveInDirectionAction(),
	))
}

func luaMethodsMoveInDirectionAction() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IMoveInDirectionAction](l, 1)
			obj := objInterface.GetMoveInDirectionAction()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IMoveInDirectionAction](l, 1)
			obj := objInterface.GetMoveInDirectionAction()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (m *MoveInDirectionAction) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = m

	l.SetMetatable(ud, l.GetTypeMetatable("MoveInDirectionAction"))
	return ud
}
