// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IImmobilize interface {
	GetImmobilize() *Immobilize
}

func (i *Immobilize) GetImmobilize() *Immobilize {
	return i
}

func registerLuaImmobilize(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Immobilize")
	state.SetGlobal("Immobilize", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsImmobilize(),
	))
}

func luaMethodsImmobilize() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IImmobilize](l, 1)
			obj := objInterface.GetImmobilize()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IImmobilize](l, 1)
			obj := objInterface.GetImmobilize()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (i *Immobilize) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = i

	l.SetMetatable(ud, l.GetTypeMetatable("Immobilize"))
	return ud
}
