// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IUseItemPosition interface {
	GetUseItemPosition() *UseItemPosition
}

func (u *UseItemPosition) GetUseItemPosition() *UseItemPosition {
	return u
}

func registerLuaUseItemPosition(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("UseItemPosition")
	state.SetGlobal("UseItemPosition", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsUseItemPosition(),
	))
}

func luaMethodsUseItemPosition() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IUseItemPosition](l, 1)
			obj := objInterface.GetUseItemPosition()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IUseItemPosition](l, 1)
			obj := objInterface.GetUseItemPosition()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (u *UseItemPosition) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = u

	l.SetMetatable(ud, l.GetTypeMetatable("UseItemPosition"))
	return ud
}
