// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IKnockDown interface {
	GetKnockDown() *KnockDown
}

func (k *KnockDown) GetKnockDown() *KnockDown {
	return k
}

func registerLuaKnockDown(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("KnockDown")
	state.SetGlobal("KnockDown", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsKnockDown(),
	))
}

func luaMethodsKnockDown() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IKnockDown](l, 1)
			obj := objInterface.GetKnockDown()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IKnockDown](l, 1)
			obj := objInterface.GetKnockDown()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (k *KnockDown) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = k

	l.SetMetatable(ud, l.GetTypeMetatable("KnockDown"))
	return ud
}
