// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type ITurnAction interface {
	GetTurnAction() *TurnAction
}

func (t *TurnAction) GetTurnAction() *TurnAction {
	return t
}

func registerLuaTurnAction(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("TurnAction")
	state.SetGlobal("TurnAction", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsTurnAction(),
	))
}

func luaMethodsTurnAction() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ITurnAction](l, 1)
			obj := objInterface.GetTurnAction()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ITurnAction](l, 1)
			obj := objInterface.GetTurnAction()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (t *TurnAction) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = t

	l.SetMetatable(ud, l.GetTypeMetatable("TurnAction"))
	return ud
}
