// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IFlee interface {
	GetFlee() *Flee
}

func (f *Flee) GetFlee() *Flee {
	return f
}

func registerLuaFlee(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Flee")
	state.SetGlobal("Flee", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsFlee(),
	))
}

func luaMethodsFlee() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IFlee](l, 1)
			obj := objInterface.GetFlee()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IFlee](l, 1)
			obj := objInterface.GetFlee()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (f *Flee) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = f

	l.SetMetatable(ud, l.GetTypeMetatable("Flee"))
	return ud
}
