// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IActivate interface {
	GetActivate() *Activate
}

func (a *Activate) GetActivate() *Activate {
	return a
}

func registerLuaActivate(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Activate")
	state.SetGlobal("Activate", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActivate(),
	))
}

func luaMethodsActivate() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"targetEntityID": lua.LuaGenericGetSetNumber[IActivate](func(v IActivate) *uint16 { return &v.GetActivate().TargetEntityID }),
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActivate](l, 1)
			obj := objInterface.GetActivate()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActivate](l, 1)
			obj := objInterface.GetActivate()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"initWithoutOpCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActivate](l, 1)
			obj := objInterface.GetActivate()
			obj.InitWithoutOpCode(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (a *Activate) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("Activate"))
	return ud
}
