// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IAmbush interface {
	GetAmbush() *Ambush
}

func (a *Ambush) GetAmbush() *Ambush {
	return a
}

func registerLuaAmbush(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Ambush")
	state.SetGlobal("Ambush", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsAmbush(),
	))
}

func luaMethodsAmbush() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IAmbush](l, 1)
			obj := objInterface.GetAmbush()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IAmbush](l, 1)
			obj := objInterface.GetAmbush()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (a *Ambush) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("Ambush"))
	return ud
}
