// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IKill interface {
	GetKill() *Kill
}

func (k *Kill) GetKill() *Kill {
	return k
}

func registerLuaKill(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Kill")
	state.SetGlobal("Kill", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsKill(),
	))
}

func luaMethodsKill() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IKill](l, 1)
			obj := objInterface.GetKill()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IKill](l, 1)
			obj := objInterface.GetKill()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (k *Kill) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = k

	l.SetMetatable(ud, l.GetTypeMetatable("Kill"))
	return ud
}
