// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IPlayAnimation interface {
	GetPlayAnimation() *PlayAnimation
}

func (p *PlayAnimation) GetPlayAnimation() *PlayAnimation {
	return p
}

func registerLuaPlayAnimation(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("PlayAnimation")
	state.SetGlobal("PlayAnimation", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsPlayAnimation(),
	))
}

func luaMethodsPlayAnimation() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayAnimation](l, 1)
			obj := objInterface.GetPlayAnimation()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayAnimation](l, 1)
			obj := objInterface.GetPlayAnimation()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (p *PlayAnimation) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = p

	l.SetMetatable(ud, l.GetTypeMetatable("PlayAnimation"))
	return ud
}
