// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IMoveTo interface {
	GetMoveTo() *MoveTo
}

func (m *MoveTo) GetMoveTo() *MoveTo {
	return m
}

func registerLuaMoveTo(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("MoveTo")
	state.SetGlobal("MoveTo", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsMoveTo(),
	))
}

func luaMethodsMoveTo() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"posX": lua.LuaGenericGetSetNumber[IMoveTo](func(v IMoveTo) *float32 { return &v.GetMoveTo().PosX }),
		"posY": lua.LuaGenericGetSetNumber[IMoveTo](func(v IMoveTo) *float32 { return &v.GetMoveTo().PosY }),
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IMoveTo](l, 1)
			obj := objInterface.GetMoveTo()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IMoveTo](l, 1)
			obj := objInterface.GetMoveTo()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (m *MoveTo) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = m

	l.SetMetatable(ud, l.GetTypeMetatable("MoveTo"))
	return ud
}
