// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IAttackTarget2 interface {
	GetAttackTarget2() *AttackTarget2
}

func (a *AttackTarget2) GetAttackTarget2() *AttackTarget2 {
	return a
}

func registerLuaAttackTarget2(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("AttackTarget2")
	state.SetGlobal("AttackTarget2", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsAttackTarget2(),
	))
}

func luaMethodsAttackTarget2() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IAttackTarget2](l, 1)
			obj := objInterface.GetAttackTarget2()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IAttackTarget2](l, 1)
			obj := objInterface.GetAttackTarget2()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (a *AttackTarget2) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("AttackTarget2"))
	return ud
}
