// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	"RainbowRunner/pkg/datatypes"
	lua2 "github.com/yuin/gopher-lua"
)

type IWarpTo interface {
	GetWarpTo() *WarpTo
}

func (w *WarpTo) GetWarpTo() *WarpTo {
	return w
}

func registerLuaWarpTo(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("WarpTo")
	state.SetGlobal("WarpTo", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsWarpTo(),
	))
}

func luaMethodsWarpTo() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"position": lua.LuaGenericGetSetValue[IWarpTo, datatypes.Vector3Float32](func(v IWarpTo) *datatypes.Vector3Float32 { return &v.GetWarpTo().Position }),
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IWarpTo](l, 1)
			obj := objInterface.GetWarpTo()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IWarpTo](l, 1)
			obj := objInterface.GetWarpTo()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (w *WarpTo) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = w

	l.SetMetatable(ud, l.GetTypeMetatable("WarpTo"))
	return ud
}
