// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IFollow interface {
	GetFollow() *Follow
}

func (f *Follow) GetFollow() *Follow {
	return f
}

func registerLuaFollow(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Follow")
	state.SetGlobal("Follow", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsFollow(),
	))
}

func luaMethodsFollow() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IFollow](l, 1)
			obj := objInterface.GetFollow()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IFollow](l, 1)
			obj := objInterface.GetFollow()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (f *Follow) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = f

	l.SetMetatable(ud, l.GetTypeMetatable("Follow"))
	return ud
}
