// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IUseItem interface {
	GetUseItem() *UseItem
}

func (u *UseItem) GetUseItem() *UseItem {
	return u
}

func registerLuaUseItem(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("UseItem")
	state.SetGlobal("UseItem", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsUseItem(),
	))
}

func luaMethodsUseItem() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IUseItem](l, 1)
			obj := objInterface.GetUseItem()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IUseItem](l, 1)
			obj := objInterface.GetUseItem()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (u *UseItem) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = u

	l.SetMetatable(ud, l.GetTypeMetatable("UseItem"))
	return ud
}
