// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IUnSpawn interface {
	GetUnSpawn() *UnSpawn
}

func (u *UnSpawn) GetUnSpawn() *UnSpawn {
	return u
}

func registerLuaUnSpawn(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("UnSpawn")
	state.SetGlobal("UnSpawn", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsUnSpawn(),
	))
}

func luaMethodsUnSpawn() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IUnSpawn](l, 1)
			obj := objInterface.GetUnSpawn()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IUnSpawn](l, 1)
			obj := objInterface.GetUnSpawn()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (u *UnSpawn) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = u

	l.SetMetatable(ud, l.GetTypeMetatable("UnSpawn"))
	return ud
}
