// Code generated by scripts/generatelua DO NOT EDIT.
package actions

import (
	lua "RainbowRunner/internal/lua"
	byter "RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IDoEffect interface {
	GetDoEffect() *DoEffect
}

func (d *DoEffect) GetDoEffect() *DoEffect {
	return d
}

func registerLuaDoEffect(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("DoEffect")
	state.SetGlobal("DoEffect", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsDoEffect(),
	))
}

func luaMethodsDoEffect() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"opCode": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IDoEffect](l, 1)
			obj := objInterface.GetDoEffect()
			res0 := obj.OpCode()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("BehaviourAction"))
			l.Push(ud)

			return 1
		},
		"init": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IDoEffect](l, 1)
			obj := objInterface.GetDoEffect()
			obj.Init(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
	})
}

func (d *DoEffect) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = d

	l.SetMetatable(ud, l.GetTypeMetatable("DoEffect"))
	return ud
}
