// Code generated by "stringer -type=AuthServerMessage"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthServerProtocolVerPacket-0]
	_ = x[AuthServerLoginFailPacket-1]
	_ = x[AuthServerBlockedAccountPacket-2]
	_ = x[AuthServerLoginOkPacket-3]
	_ = x[AuthServerSendServerListExPacket-4]
	_ = x[AuthServerSendServerFailPacket-5]
	_ = x[AuthServerPlayFailPacket-6]
	_ = x[AuthServerPlayOkPacket-7]
	_ = x[AuthServerAccountKickedPacket-8]
	_ = x[AuthServerBlockedAccountWithMessagePacket-9]
	_ = x[AuthServerCSCCheckPacket-10]
	_ = x[AuthServerQueueSizePacket-11]
	_ = x[AuthServerHandoffToQueuePacket-12]
	_ = x[AuthServerPositionInQueuePacket-13]
	_ = x[AuthServerHandoffToGamePacket-14]
}

const _AuthServerMessage_name = "AuthServerProtocolVerPacketAuthServerLoginFailPacketAuthServerBlockedAccountPacketAuthServerLoginOkPacketAuthServerSendServerListExPacketAuthServerSendServerFailPacketAuthServerPlayFailPacketAuthServerPlayOkPacketAuthServerAccountKickedPacketAuthServerBlockedAccountWithMessagePacketAuthServerCSCCheckPacketAuthServerQueueSizePacketAuthServerHandoffToQueuePacketAuthServerPositionInQueuePacketAuthServerHandoffToGamePacket"

var _AuthServerMessage_index = [...]uint16{0, 27, 52, 82, 105, 137, 167, 191, 213, 242, 283, 307, 332, 362, 393, 422}

func (i AuthServerMessage) String() string {
	if i < 0 || i >= AuthServerMessage(len(_AuthServerMessage_index)-1) {
		return "AuthServerMessage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthServerMessage_name[_AuthServerMessage_index[i]:_AuthServerMessage_index[i+1]]
}
