// Code generated by "stringer -type=OpType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpTypeAvatarMovement-0]
	_ = x[OpTypeCreateNPC-1]
	_ = x[OpTypeEquippedItemClickResponse-2]
	_ = x[OpTypeInventoryItemClickResponse-3]
	_ = x[OpTypeInventoryItemDropResponse-4]
	_ = x[OpTypeOther-5]
	_ = x[OpTypeBehaviourAction-6]
	_ = x[OpTypeSkills-7]
	_ = x[OpTypeManipulators-8]
	_ = x[OpTypeCreateEntity-9]
	_ = x[OpTypeAvatarMovementOthers-10]
}

const _OpType_name = "OpTypeAvatarMovementOpTypeCreateNPCOpTypeEquippedItemClickResponseOpTypeInventoryItemClickResponseOpTypeInventoryItemDropResponseOpTypeOtherOpTypeBehaviourActionOpTypeSkillsOpTypeManipulatorsOpTypeCreateEntityOpTypeAvatarMovementOthers"

var _OpType_index = [...]uint8{0, 20, 35, 66, 98, 129, 140, 161, 173, 191, 209, 235}

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
