// Code generated by "stringer -type=OpType"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpTypeAvatarMovement-0]
	_ = x[OpTypeCreateNPC-1]
	_ = x[OpTypeEquippedItemClickResponse-2]
	_ = x[OpTypeOther-3]
}

const _OpType_name = "OpTypeAvatarMovementOpTypeCreateNPCOpTypeEquippedItemClickResponseOpTypeOther"

var _OpType_index = [...]uint8{0, 20, 35, 66, 77}

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
