package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IZonePortal interface {
	GetZonePortal() *ZonePortal
}

func (z *ZonePortal) GetZonePortal() *ZonePortal {
	return z
}

func registerLuaZonePortal(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ZonePortal")
	state.SetGlobal("ZonePortal", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaZonePortal))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsZonePortal(),
	))
}

func luaMethodsZonePortal() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"unk0":   luaGenericGetSetString[IZonePortal](func(v IZonePortal) *string { return &v.GetZonePortal().Unk0 }),
		"unk1":   luaGenericGetSetString[IZonePortal](func(v IZonePortal) *string { return &v.GetZonePortal().Unk1 }),
		"width":  luaGenericGetSetNumber[IZonePortal](func(v IZonePortal) *uint16 { return &v.GetZonePortal().Width }),
		"height": luaGenericGetSetNumber[IZonePortal](func(v IZonePortal) *uint16 { return &v.GetZonePortal().Height }),
		"unk4":   luaGenericGetSetNumber[IZonePortal](func(v IZonePortal) *uint32 { return &v.GetZonePortal().Unk4 }),
		"target": luaGenericGetSetString[IZonePortal](func(v IZonePortal) *string { return &v.GetZonePortal().Target }),
		"activate": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IZonePortal](l, 1)
			obj := objInterface.GetZonePortal()
			obj.Activate(
				lua.CheckReferenceValue[RRPlayer](l, 2),
				lua.CheckReferenceValue[UnitBehavior](l, 3), byte(l.CheckNumber(4)),
			)

			return 0
		},
		"writeInit": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IZonePortal](l, 1)
			obj := objInterface.GetZonePortal()
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"getZonePortal": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IZonePortal](l, 1)
			obj := objInterface.GetZonePortal()
			res0 := obj.GetZonePortal()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("ZonePortal"))
			l.Push(ud)

			return 1
		},
	}, luaMethodsWorldEntity)
}
func newLuaZonePortal(l *lua2.LState) int {
	obj := NewZonePortal(string(l.CheckString(1)), string(l.CheckString(2)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ZonePortal"))
	l.Push(ud)
	return 1
}

func (z *ZonePortal) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = z

	l.SetMetatable(ud, l.GetTypeMetatable("ZonePortal"))
	return ud
}
