package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	"RainbowRunner/internal/connections"
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaGCObject(state *lua2.LState) {
	mt := state.NewTypeMetatable("GCObject")
	state.SetGlobal("GCObject", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaGCObject))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsGCObject(),
	))
}

func luaMethodsGCObject() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"version":      luaGenericGetSetNumber[GCObject, uint8](func(v GCObject) *uint8 { return &v.Version }),
		"gcnativeType": luaGenericGetSetString[GCObject](func(v GCObject) *string { return &v.GCNativeType }),
		"gclabel":      luaGenericGetSetString[GCObject](func(v GCObject) *string { return &v.GCLabel }),
		"gctype":       luaGenericGetSetString[GCObject](func(v GCObject) *string { return &v.GCType }),
		"activate": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.Activate(
				lua.CheckReferenceValue[RRPlayer](l, 1),
				lua.CheckReferenceValue[UnitBehavior](l, 2),
				lua.CheckValue[byte](l, 3),
			)

			return 0
		},
		"string": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.String()
			l.Push(lua2.LString(res0))

			return 1
		},
		"setOwner": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.SetOwner(
				lua.CheckReferenceValue[connections.RRConn](l, 1),
			)

			return 0
		},
		"removeChildAt": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.RemoveChildAt(
				int(l.CheckNumber(1)),
			)

			return 0
		},
		"type": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.Type()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("DRObjectType"))
			l.Push(ud)

			return 1
		},
		"id": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.ID()
			l.Push(lua2.LNumber(res0))

			return 1
		},
		"readUpdate": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.ReadUpdate(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("error"))
			l.Push(ud)

			return 1
		},
		"writeSynch": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.WriteSynch(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"tick": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.Tick()

			return 0
		},
		"getGCObject": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.GetGCObject()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("GCObject"))
			l.Push(ud)

			return 1
		},
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeUpdate": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.WriteUpdate(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"ownerID": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.OwnerID()
			l.Push(lua2.LNumber(res0))

			return 1
		},
		"children": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.Children()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("[]DRObject"))
			l.Push(ud)

			return 1
		},
		"rrentityProperties": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.RREntityProperties()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("RREntityProperties"))
			l.Push(ud)

			return 1
		},
		"writeFullGCObject": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.WriteFullGCObject(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"addChild": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.AddChild(
				lua.CheckValue[DRObject](l, 1),
			)

			return 0
		},
		"getChildByGCNativeType": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.GetChildByGCNativeType(
				l.CheckString(1),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("DRObject"))
			l.Push(ud)

			return 1
		},
		"getChildByGCType": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			res0 := obj.GetChildByGCType(
				l.CheckString(1),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("DRObject"))
			l.Push(ud)

			return 1
		},
		"setVersion": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.SetVersion(
				uint8(l.CheckNumber(1)),
			)

			return 0
		},
		"readData": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.ReadData(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"walkChildren": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[GCObject](l, 1)
			obj.WalkChildren(
				lua.CheckValue[func(object DRObject)](l, 1),
			)

			return 0
		},
	})
}

func newLuaGCObject(l *lua2.LState) int {
	obj := NewGCObject(
		l.CheckString(1),
	)
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("GCObject"))
	l.Push(ud)
	return 1
}
