package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/internal/types"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaEquipment(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Equipment")
	state.SetGlobal("Equipment", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaEquipment))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsEquipment(),
	))
}

func luaMethodsEquipment() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Equipment](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeManipulatorInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Equipment](l, 1)
			obj.WriteManipulatorInit(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
	}, luaMethodsItem)
}
func newLuaEquipment(l *lua2.LState) int {
	obj := NewEquipment(string(l.CheckString(1)), string(l.CheckString(2)),
		lua.CheckValue[ItemType](l, 3),
		lua.CheckValue[types.EquipmentSlot](l, 4),
	)
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Equipment"))
	l.Push(ud)
	return 1
}
