// Code generated by scripts/generatelua DO NOT EDIT.
package objects

import (
	lua "RainbowRunner/internal/lua"
	lua2 "github.com/yuin/gopher-lua"
)

type IActivePassiveSkill interface {
	GetActivePassiveSkill() *ActivePassiveSkill
}

func (a *ActivePassiveSkill) GetActivePassiveSkill() *ActivePassiveSkill {
	return a
}

func registerLuaActivePassiveSkill(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ActivePassiveSkill")
	state.SetGlobal("ActivePassiveSkill", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaActivePassiveSkill))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsActivePassiveSkill(),
	))
}

func luaMethodsActivePassiveSkill() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"getActivePassiveSkill": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IActivePassiveSkill](l, 1)
			obj := objInterface.GetActivePassiveSkill()
			res0 := obj.GetActivePassiveSkill()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	}, luaMethodsSkill)
}
func newLuaActivePassiveSkill(l *lua2.LState) int {
	obj := NewActivePassiveSkill(string(l.CheckString(1)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ActivePassiveSkill"))
	l.Push(ud)
	return 1
}

func (a *ActivePassiveSkill) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("ActivePassiveSkill"))
	return ud
}
