// Code generated by scripts/generatelua DO NOT EDIT.
package objects

import (
	lua "RainbowRunner/internal/lua"
	lua2 "github.com/yuin/gopher-lua"
)

type IComponent interface {
	GetComponent() *Component
}

func (c *Component) GetComponent() *Component {
	return c
}

func registerLuaComponent(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Component")
	state.SetGlobal("Component", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaComponent))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsComponent(),
	))
}

func luaMethodsComponent() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"getComponent": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IComponent](l, 1)
			obj := objInterface.GetComponent()
			res0 := obj.GetComponent()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("Component"))
			l.Push(ud)

			return 1
		},
	}, luaMethodsGCObject)
}
func newLuaComponent(l *lua2.LState) int {
	obj := NewComponent(string(l.CheckString(1)), string(l.CheckString(2)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Component"))
	l.Push(ud)
	return 1
}

func (c *Component) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = c

	l.SetMetatable(ud, l.GetTypeMetatable("Component"))
	return ud
}
