// Code generated by scripts/generatelua DO NOT EDIT.
package objects

import (
	lua "RainbowRunner/internal/lua"
	lua2 "github.com/yuin/gopher-lua"
)

type IAnimation interface {
	GetAnimation() *Animation
}

func (a *Animation) GetAnimation() *Animation {
	return a
}

func registerLuaAnimation(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Animation")
	state.SetGlobal("Animation", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaAnimation))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsAnimation(),
	))
}

func luaMethodsAnimation() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"id":               lua.LuaGenericGetSetNumber[IAnimation](func(v IAnimation) *int { return &v.GetAnimation().ID }),
		"numFrames":        lua.LuaGenericGetSetNumber[IAnimation](func(v IAnimation) *int { return &v.GetAnimation().NumFrames }),
		"triggerTime":      lua.LuaGenericGetSetNumber[IAnimation](func(v IAnimation) *int { return &v.GetAnimation().TriggerTime }),
		"soundTriggerTime": lua.LuaGenericGetSetNumber[IAnimation](func(v IAnimation) *int { return &v.GetAnimation().SoundTriggerTime }),
		"animationID":      lua.LuaGenericGetSetNumber[IAnimation](func(v IAnimation) *int { return &v.GetAnimation().AnimationID }),

		"getAnimation": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IAnimation](l, 1)
			obj := objInterface.GetAnimation()
			res0 := obj.GetAnimation()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	})
}
func newLuaAnimation(l *lua2.LState) int {
	obj := NewAnimation()
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Animation"))
	l.Push(ud)
	return 1
}

func (a *Animation) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = a

	l.SetMetatable(ud, l.GetTypeMetatable("Animation"))
	return ud
}
