package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaComponent(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Component")
	state.SetGlobal("Component", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaComponent))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsComponent(),
	))
}

func luaMethodsComponent() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{}, luaMethodsGCObject)
}
func newLuaComponent(l *lua2.LState) int {
	obj := NewComponent(string(l.CheckString(1)), string(l.CheckString(2)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Component"))
	l.Push(ud)
	return 1
}
