package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	"RainbowRunner/pkg/datatypes"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaUnit(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Unit")
	state.SetGlobal("Unit", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaUnit))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsUnit(),
	))
}

func luaMethodsUnit() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"hp":                luaGenericGetSetNumber[Unit, int](func(v Unit) *int { return &v.HP }),
		"mp":                luaGenericGetSetNumber[Unit, int](func(v Unit) *int { return &v.MP }),
		"unk20CaseEntityID": luaGenericGetSetNumber[Unit, uint16](func(v Unit) *uint16 { return &v.Unk20CaseEntityID }),
		"unk40Case0":        luaGenericGetSetNumber[Unit, uint16](func(v Unit) *uint16 { return &v.Unk40Case0 }),
		"unk40Case1":        luaGenericGetSetNumber[Unit, uint16](func(v Unit) *uint16 { return &v.Unk40Case1 }),
		"unk40Case2":        luaGenericGetSetNumber[Unit, uint16](func(v Unit) *uint16 { return &v.Unk40Case2 }),
		"getUnit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Unit](l, 1)
			res0 := obj.GetUnit()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("Unit"))
			l.Push(ud)

			return 1
		},
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Unit](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"warp": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Unit](l, 1)
			obj.Warp(
				lua.CheckValue[datatypes.Vector3Float32](l, 2),
			)

			return 0
		},
		"toLua": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Unit](l, 1)
			res0 := obj.ToLua(
				lua.CheckReferenceValue[lua2.LState](l, 2),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("lua2.LValue"))
			l.Push(ud)

			return 1
		},
		"WorldEntity": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Unit](l, 1)
			l.Push(obj.WorldEntity.ToLua(l))
			return 1
		},
	})
}
func newLuaUnit(l *lua2.LState) int {
	obj := NewUnit(string(l.CheckString(1)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Unit"))
	l.Push(ud)
	return 1
}

func (u *Unit) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = u

	l.SetMetatable(ud, l.GetTypeMetatable("Unit"))
	return ud
}
