package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaAvatar(state *lua2.LState) {
	mt := state.NewTypeMetatable("Avatar")
	state.SetGlobal("Avatar", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaAvatar))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsAvatar(),
	))
}

func luaMethodsAvatar() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"rotation":   luaGenericGetSetNumber[Avatar, int32](func(v Avatar) *int32 { return &v.Rotation }),
		"moveUpdate": luaGenericGetSetNumber[Avatar, int](func(v Avatar) *int { return &v.MoveUpdate }),
		"type": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			res0 := obj.Type()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("DRObjectType"))
			l.Push(ud)

			return 1
		},
		"writeFullGCObject": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			obj.WriteFullGCObject(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeUpdate": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			obj.WriteUpdate(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"tick": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			obj.Tick()

			return 0
		},
		"getUnitBehaviourID": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			res0 := obj.GetUnitBehaviourID()
			l.Push(lua2.LNumber(res0))

			return 1
		},
		"send": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			obj.Send(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"sendFollowClient": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			obj.SendFollowClient()

			return 0
		},
		"warp": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			obj.Warp(
				float32(l.CheckNumber(1)),
				float32(l.CheckNumber(2)),
				float32(l.CheckNumber(3)),
			)

			return 0
		},
		"sendMoveTo": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			obj.SendMoveTo(
				uint8(l.CheckNumber(1)),
				uint16(l.CheckNumber(2)),
				float32(l.CheckNumber(3)),
				float32(l.CheckNumber(4)),
			)

			return 0
		},
		"getUnitContainer": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			res0 := obj.GetUnitContainer()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("UnitContainer"))
			l.Push(ud)

			return 1
		},
		"getManipulators": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			res0 := obj.GetManipulators()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("Manipulators"))
			l.Push(ud)

			return 1
		},
		"getUnitBehaviour": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Avatar](l, 1)
			res0 := obj.GetUnitBehaviour()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("UnitBehavior"))
			l.Push(ud)

			return 1
		},
	}, luaMethodsGCObject)
}

func newLuaAvatar(l *lua2.LState) int {
	obj := NewAvatar(
		l.CheckString(1),
	)
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Avatar"))
	l.Push(ud)
	return 1
}
