package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaStockUnit(state *lua2.LState) {
	mt := state.NewTypeMetatable("StockUnit")
	state.SetGlobal("StockUnit", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaStockUnit))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsStockUnit(),
	))
}

func luaMethodsStockUnit() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[StockUnit](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
	}, luaMethodsUnit)
}

func newLuaStockUnit(l *lua2.LState) int {
	obj := NewStockUnit(
		l.CheckString(1),
	)
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("StockUnit"))
	l.Push(ud)
	return 1
}
