package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaPlayer(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Player")
	state.SetGlobal("Player", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaPlayer))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsPlayer(),
	))
}

func luaMethodsPlayer() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"name":      luaGenericGetSetString[Player](func(v Player) *string { return &v.Name }),
		"currentHP": luaGenericGetSetNumber[Player, uint32](func(v Player) *uint32 { return &v.CurrentHP }),
		"type": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Player](l, 1)
			res0 := obj.Type()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("DRObjectType"))
			l.Push(ud)

			return 1
		},
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Player](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeUpdate": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Player](l, 1)
			obj.WriteUpdate(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeFullGCObject": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Player](l, 1)
			obj.WriteFullGCObject(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeSynch": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Player](l, 1)
			obj.WriteSynch(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"sendCreateNewPlayerEntity": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Player](l, 1)
			obj.SendCreateNewPlayerEntity(
				lua.CheckReferenceValue[RRPlayer](l, 1),
			)

			return 0
		},
	}, luaMethodsGCObject)
}
func newLuaPlayer(l *lua2.LState) int {
	obj := NewPlayer(string(l.CheckString(1)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Player"))
	l.Push(ud)
	return 1
}
