// Code generated by scripts/generatelua DO NOT EDIT.
package objects

import (
	lua "RainbowRunner/internal/lua"
	lua2 "github.com/yuin/gopher-lua"
)

type IHero interface {
	GetHero() *Hero
}

func (h *Hero) GetHero() *Hero {
	return h
}

func registerLuaHero(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Hero")
	state.SetGlobal("Hero", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaHero))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsHero(),
	))
}

func luaMethodsHero() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{}, luaMethodsUnit)
}
func newLuaHero(l *lua2.LState) int {
	obj := NewHero(string(l.CheckString(1)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Hero"))
	l.Push(ud)
	return 1
}

func (h *Hero) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = h

	l.SetMetatable(ud, l.GetTypeMetatable("Hero"))
	return ud
}
