package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaModifiers(state *lua2.LState) {
	mt := state.NewTypeMetatable("Modifiers")
	state.SetGlobal("Modifiers", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaModifiers))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsModifiers(),
	))
}

func luaMethodsModifiers() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[Modifiers](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
	}, luaMethodsComponent)
}

func newLuaModifiers(l *lua2.LState) int {
	obj := NewModifiers(
		l.CheckString(1),
	)
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Modifiers"))
	l.Push(ud)
	return 1
}
