package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaRRPlayer(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("RRPlayer")
	state.SetGlobal("RRPlayer", mt)
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsRRPlayer(),
	))
}

func luaMethodsRRPlayer() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"onZoneJoin": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[RRPlayer](l, 1)
			obj.OnZoneJoin()

			return 0
		},
		"leaveZone": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[RRPlayer](l, 1)
			obj.LeaveZone()

			return 0
		},
		"joinZone": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[RRPlayer](l, 1)
			obj.JoinZone(
				lua.CheckReferenceValue[Zone](l, 1),
			)

			return 0
		},
	})
}
