// Code generated by scripts/generatelua DO NOT EDIT.
package objects

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type IPlayer interface {
	GetPlayer() *Player
}

func (p *Player) GetPlayer() *Player {
	return p
}

func registerLuaPlayer(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Player")
	state.SetGlobal("Player", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaPlayer))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsPlayer(),
	))
}

func luaMethodsPlayer() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{
		"name":      lua.LuaGenericGetSetString[IPlayer](func(v IPlayer) *string { return &v.GetPlayer().Name }),
		"currentHP": lua.LuaGenericGetSetNumber[IPlayer](func(v IPlayer) *uint32 { return &v.GetPlayer().CurrentHP }),
		"spawned":   lua.LuaGenericGetSetBool[IPlayer](func(v IPlayer) *bool { return &v.GetPlayer().Spawned }),
		"zone":      lua.LuaGenericGetSetValueAny[IPlayer](func(v IPlayer) **Zone { return &v.GetPlayer().Zone }),

		"type": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			res0 := obj.Type()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("drobjecttypes.DRObjectType"))
			l.Push(ud)

			return 1
		},

		"writeInit": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"writeUpdate": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.WriteUpdate(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"writeFullGCObject": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.WriteFullGCObject(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"writeSynch": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.WriteSynch(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"writeCreateNewPlayerEntity": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.WriteCreateNewPlayerEntity(
				lua.CheckReferenceValue[ClientEntityWriter](l, 2), bool(l.CheckBool(3)),
			)

			return 0
		},

		"changeZone": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.ChangeZone(string(l.CheckString(2)))

			return 0
		},

		"joinZone": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.JoinZone(
				lua.CheckReferenceValue[Zone](l, 2),
			)

			return 0
		},

		"onZoneJoin": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.OnZoneJoin()

			return 0
		},

		"onZoneLeave": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.OnZoneLeave()

			return 0
		},

		"leaveZone": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			obj.LeaveZone()

			return 0
		},

		"getPlayer": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[IPlayer](l, 1)
			obj := objInterface.GetPlayer()
			res0 := obj.GetPlayer()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	}, luaMethodsGCObject)
}
func newLuaPlayer(l *lua2.LState) int {
	obj := NewPlayer(string(l.CheckString(1)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Player"))
	l.Push(ud)
	return 1
}

func (p *Player) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = p

	l.SetMetatable(ud, l.GetTypeMetatable("Player"))
	return ud
}
