// Code generated by scripts/generatelua DO NOT EDIT.
package objects

import (
	lua "RainbowRunner/internal/lua"
	lua2 "github.com/yuin/gopher-lua"
)

type IEntity interface {
	GetEntity() *Entity
}

func (e *Entity) GetEntity() *Entity {
	return e
}

func registerLuaEntity(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Entity")
	state.SetGlobal("Entity", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaEntity))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsEntity(),
	))
}

func luaMethodsEntity() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{}, luaMethodsGCObject)
}
func newLuaEntity(l *lua2.LState) int {
	obj := NewEntity(string(l.CheckString(1)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Entity"))
	l.Push(ud)
	return 1
}

func (e *Entity) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = e

	l.SetMetatable(ud, l.GetTypeMetatable("Entity"))
	return ud
}
