package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaUnitContainer(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("UnitContainer")
	state.SetGlobal("UnitContainer", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaUnitContainer))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsUnitContainer(),
	))
}

func luaMethodsUnitContainer() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"readUpdate": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[UnitContainer](l, 1)
			res0 := obj.ReadUpdate(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("error"))
			l.Push(ud)

			return 1
		},
		"writeFullGCObject": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[UnitContainer](l, 1)
			obj.WriteFullGCObject(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"setActiveItem": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[UnitContainer](l, 1)
			obj.SetActiveItem(
				lua.CheckValue[DRObject](l, 1),
			)

			return 0
		},
		"writeSetActiveItem": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[UnitContainer](l, 1)
			obj.WriteSetActiveItem(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeClearActiveItem": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[UnitContainer](l, 1)
			obj.WriteClearActiveItem(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
		"writeRemoveItem": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[UnitContainer](l, 1)
			obj.WriteRemoveItem(
				lua.CheckReferenceValue[byter.Byter](l, 1), uint32(l.CheckNumber(2)),
			)

			return 0
		},
		"writeAddItem": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[UnitContainer](l, 1)
			obj.WriteAddItem(
				lua.CheckReferenceValue[byter.Byter](l, 1),
				lua.CheckValue[DRObject](l, 2),
				lua.CheckReferenceValue[Inventory](l, 3),
				lua.CheckValue[byte](l, 4),
				lua.CheckValue[byte](l, 5),
			)

			return 0
		},
		"getInventoryByID": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[UnitContainer](l, 1)
			res0 := obj.GetInventoryByID(
				lua.CheckValue[byte](l, 1),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("Inventory"))
			l.Push(ud)

			return 1
		},
	}, luaMethodsComponent)
}
func newLuaUnitContainer(l *lua2.LState) int {
	obj := NewUnitContainer(
		lua.CheckValue[DRObject](l, 1), string(l.CheckString(2)),
		lua.CheckReferenceValue[Avatar](l, 3),
	)
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("UnitContainer"))
	l.Push(ud)
	return 1
}
