package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	"RainbowRunner/pkg/datatypes"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaNPC(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("NPC")
	state.SetGlobal("NPC", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaNPC))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsNPC(),
	))
}

func luaMethodsNPC() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"name":  luaGenericGetSetString[NPC](func(v NPC) *string { return &v.Name }),
		"level": luaGenericGetSetNumber[NPC, int32](func(v NPC) *int32 { return &v.Level }),
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[NPC](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},
		"toLua": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[NPC](l, 1)
			res0 := obj.ToLua(
				lua.CheckReferenceValue[lua2.LState](l, 2),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("lua2.LValue"))
			l.Push(ud)

			return 1
		},
		"Unit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[NPC](l, 1)
			l.Push(obj.Unit.ToLua(l))
			return 1
		},
	})
}
func newLuaNPC(l *lua2.LState) int {
	obj := NewNPC(string(l.CheckString(1)), string(l.CheckString(2)),
		lua.CheckValue[datatypes.Vector3Float32](l, 3), float32(l.CheckNumber(4)),
	)
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("NPC"))
	l.Push(ud)
	return 1
}

func (n *NPC) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = n

	l.SetMetatable(ud, l.GetTypeMetatable("NPC"))
	return ud
}
