package objects

/**
 * This file is generated by scripts/generatelua/generatelua.go
 * DO NOT EDIT
 */

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

func registerLuaItemObject(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("ItemObject")
	state.SetGlobal("ItemObject", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaItemObject))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsItemObject(),
	))
}

func luaMethodsItemObject() map[string]lua2.LGFunction {
	return luaMethodsExtend(map[string]lua2.LGFunction{
		"type": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[ItemObject](l, 1)
			res0 := obj.Type()
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("DRObjectType"))
			l.Push(ud)

			return 1
		},
		"writeInit": func(l *lua2.LState) int {
			obj := lua.CheckReferenceValue[ItemObject](l, 1)
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 1),
			)

			return 0
		},
	}, luaMethodsWorldEntity)
}
func newLuaItemObject(l *lua2.LState) int {
	obj := NewItemObject(string(l.CheckString(1)),
		lua.CheckValue[DRObject](l, 2),
	)
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("ItemObject"))
	l.Push(ud)
	return 1
}
