// Code generated by scripts/generatelua DO NOT EDIT.
package objects

import (
	lua "RainbowRunner/internal/lua"
	"RainbowRunner/pkg/byter"
	lua2 "github.com/yuin/gopher-lua"
)

type ISkills interface {
	GetSkills() *Skills
}

func (s *Skills) GetSkills() *Skills {
	return s
}

func registerLuaSkills(state *lua2.LState) {
	// Ensure the import is referenced in code
	_ = lua.LuaScript{}

	mt := state.NewTypeMetatable("Skills")
	state.SetGlobal("Skills", mt)
	state.SetField(mt, "new", state.NewFunction(newLuaSkills))
	state.SetField(mt, "__index", state.SetFuncs(state.NewTable(),
		luaMethodsSkills(),
	))
}

func luaMethodsSkills() map[string]lua2.LGFunction {
	return lua.LuaMethodsExtend(map[string]lua2.LGFunction{

		"readUpdate": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.ReadUpdate(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("error"))
			l.Push(ud)

			return 1
		},

		"getSkillInSlot": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.GetSkillInSlot(uint32(l.CheckNumber(2)))
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("ISkill"))
			l.Push(ud)

			return 1
		},

		"writeInit": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			obj.WriteInit(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)

			return 0
		},

		"getAllSkills": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.GetAllSkills()
			res0Array := l.NewTable()

			for _, res0 := range res0 {
				ud := l.NewUserData()
				ud.Value = res0
				l.SetMetatable(ud, l.GetTypeMetatable("[]ISkill"))
				res0Array.Append(ud)
			}

			l.Push(res0Array)

			return 1
		},

		"getActivePassiveSkills": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.GetActivePassiveSkills()
			res0Array := l.NewTable()

			for _, res0 := range res0 {
				if res0 != nil {
					res0Array.Append(res0.ToLua(l))
				} else {
					res0Array.Append(lua2.LNil)
				}
			}

			l.Push(res0Array)

			return 1
		},

		"getPassiveSkills": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.GetPassiveSkills()
			res0Array := l.NewTable()

			for _, res0 := range res0 {
				if res0 != nil {
					res0Array.Append(res0.ToLua(l))
				} else {
					res0Array.Append(lua2.LNil)
				}
			}

			l.Push(res0Array)

			return 1
		},

		"getActiveSkills": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.GetActiveSkills()
			res0Array := l.NewTable()

			for _, res0 := range res0 {
				if res0 != nil {
					res0Array.Append(res0.ToLua(l))
				} else {
					res0Array.Append(lua2.LNil)
				}
			}

			l.Push(res0Array)

			return 1
		},

		"unequipSkill": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.UnequipSkill(
				lua.CheckValue[ISkill](l, 2),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("error"))
			l.Push(ud)

			return 1
		},

		"equipSkill": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.EquipSkill(
				lua.CheckValue[ISkill](l, 2), uint32(l.CheckNumber(3)),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("error"))
			l.Push(ud)

			return 1
		},

		"addSkill": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			obj.AddSkill(
				lua.CheckReferenceValue[ActiveSkill](l, 2), int(l.CheckNumber(3)), int(l.CheckNumber(4)),
			)

			return 0
		},

		"getSkillByGCTypeRequest": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.GetSkillByGCTypeRequest(
				lua.CheckReferenceValue[byter.Byter](l, 2),
			)
			ud := l.NewUserData()
			ud.Value = res0
			l.SetMetatable(ud, l.GetTypeMetatable("ISkill"))
			l.Push(ud)

			return 1
		},

		"getSkillSlots": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.GetSkillSlots()
			res0Array := l.NewTable()

			for _, res0 := range res0 {
				ud := l.NewUserData()
				ud.Value = res0
				l.SetMetatable(ud, l.GetTypeMetatable("[]ISkillSlot"))
				res0Array.Append(ud)
			}

			l.Push(res0Array)

			return 1
		},

		"getSkills": func(l *lua2.LState) int {
			objInterface := lua.CheckInterfaceValue[ISkills](l, 1)
			obj := objInterface.GetSkills()
			res0 := obj.GetSkills()
			if res0 != nil {
				l.Push(res0.ToLua(l))
			} else {
				l.Push(lua2.LNil)
			}

			return 1
		},
	}, luaMethodsComponent)
}
func newLuaSkills(l *lua2.LState) int {
	obj := NewSkills(string(l.CheckString(1)))
	ud := l.NewUserData()
	ud.Value = obj

	l.SetMetatable(ud, l.GetTypeMetatable("Skills"))
	l.Push(ud)
	return 1
}

func (s *Skills) ToLua(l *lua2.LState) lua2.LValue {
	ud := l.NewUserData()
	ud.Value = s

	l.SetMetatable(ud, l.GetTypeMetatable("Skills"))
	return ud
}
